### ISSUE TITLE
Struct for storing SVGs

### ISSUE THREAD

**Issue by AmirJahan** [AmirJahan/Moush#11]
We need a struct that serializes each SVG  and sets it ready to be written to the Firebase.

**Comment by PG23Melissa** [comment]
May 5 2023

Don’t make everything public, that means every file that is saved, it need a descriptions whenever is public or private.

When you are running a search it will only search for the public ones

Make this a struct and do a couple of random objects andresearch for ways to connect.

The owner of the firebase project is Amir

 Sign in methods:
E-Mail and Google
